name: isaaclab_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-cuda=12.4
  - pip=23.0
  - pip:
    - 'isaacsim[all,extscache]==4.5.0'
