name: isaaclab_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip=23.0
  - pip:
    - 'isaacsim[all,extscache]==4.5.0'
